pro/pro/Controllers/extraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using pro.Models;

namespace pro.Controllers
{
    public class extraController : Controller
    {
        dbaseEntities1 db = new dbaseEntities1();
        //
        // GET: /extra/

        public ActionResult Index()
        {
            @ViewBag.data = db.cities.OrderBy(y => y.cityname);
            return View();
        }
        [HttpPost]
        public ActionResult area(int selectedvalue)
        {
            List<string> objcity = new List<string>();
            objcity = db.areas.Where(m => m.cid == selectedvalue).Select(m => m.areaname).ToList();

           // SelectList obgcity = new SelectList(objcity, "id", "areaname", 0);
            return Json(new{Objcity = objcity});
        }
       
        
        

    }
}

pro/pro/Views/Shared/Partial1.cshtml
index

pro/pro/Views/Shared/_layout.cshtml
@using pro.Models
@{
    dbaseEntities1 db = new dbaseEntities1();
    List<menu> menus = db.menus.OrderBy(x => x.name).ToList();
    ViewBag.menulist = menus;
    var Users = (List<menu>)ViewBag.menulist;
}
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>@ViewBag.title</title>
<link rel="stylesheet" href="@Url.Content("~/Content/styles.css")" type="text/css" />
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
</head>
<body>

<div id="sitename">
			<div class="width">
				<h1><a href="#"> Sell Me </a></h1>

				<nav>
					<ul>
        					<li><a href="~/Home/index">Home</a></li>
        	    			
         	   				@if(@ViewBag.user!=null)
                 {
                     <li><a href="/login/Index">Hi @ViewBag.user</a></li>
                     <li class="end"><a href="/login/logout">Logout</a></li>
                 }
               
        				</ul>
				</nav>
	
				<div class="clear"></div>
			</div>
		</div>
		
        <table>
        <tr>
        <td id="content">@RenderBody()</td></tr>
        
    </table>

pro/pro/Views/Shared/admin.cshtml
@using pro.Models
@{
    ViewBag.Title = "admin";
    Layout = "~/Views/Shared/_layout.cshtml";
    dbaseEntities1 db = new dbaseEntities1();
    List<menu> menus = db.menus.OrderBy(x => x.name).ToList();
    ViewBag.menulist = menus;
    var Category = (List<menu>)ViewBag.menulist;
}


<!doctype html>
<html lang=''>
<head>
   <meta charset='utf-8'>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../../Content/styles2.css" rel="stylesheet" type="text/css" />
   <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
   
    <script src="../../Scripts/script.js" type="text/javascript"></script>
   <title>Menu</title>
</head>
<body>

<table><tr>
<td>
<div id='cssmenu'>
<ul>
   <li class='active'><a href='#'><span>Home</span></a></li>
   
  
   <li class='has-sub'><a href='#'><span>ADD REQUESTS</span></a>
      <ul>
      @foreach (var i in Category)
      {

          foreach (var item in Category.Where(a => a.parentid == i.id))
      {
         
         <li class='last'><a>@Html.ActionLink(item.name, "Ads", new { name = item.name })</a></li>
         
      }
      }
      </ul>
   </li>
   <li class='has-sub'><a href='addmenu'><span>ADD SUB MENUS</span></a>
   </li>
   <li class='last'><a href='#'><span>Contact</span></a></li>
</ul>
</div>
</td>
        <td id="content">@RenderBody()</td></tr>
        
    </table>

</body>
<html>

pro/pro/Views/Shared/layout.cshtml
@using pro.Models
@{
    dbaseEntities1 db = new dbaseEntities1();
    List<menu> menus = db.menus.OrderBy(x => x.name).ToList();
    ViewBag.menulist = menus;
    var Users = (List<menu>)ViewBag.menulist;
}
<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/login.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>নাজিম অ্যাপ্লিকেশন</title>
<link rel="stylesheet" href="@Url.Content("~/Content/styles.css")" type="text/css" />
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
</head>
<body>

    <div id="sitename">
        <div class="width">
            <h1><a href="#">Sell Me</a></h1>

            <nav>
                <ul>
                    <li class="start selected"><a href="/Home/index">Home</a></li>
                    <li class="end"><a href="/contact/Index">Contact</a></li>
                    @*<li><a href="#">Products</a></li>*@
                    @if(Session["username"]!=null)
                 {
                     <li><a>Hi @Session["username"]</a></li>
                     <li class="end"><a href="/login/logout">Logout</a></li>
                 }
                 else
                    { <li><a data-toggle="modal" href="#LoginModal"><b>Login</b></a></li> 
                    
                    }
                    

        <!-- Modal -->
        <div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="CmapModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Login</h4>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("verify", "login", FormMethod.Post))
                        {
                            <div class="imgcontainer">
                                <img src="~/photo/limg.jpg" alt="Avatar" class="avatar">
                            </div>

                            <div class="container1">
                                <table>
                                    <tr>
                                        <td><label><b>Username</b></label></td>
                                        <td><input type="text" placeholder="Enter Username" name="username" required></td>
                                    </tr>
                                    <tr>
                                        <td><label><b>Password</b></label></td>
                                        <td><input type="password" placeholder="Enter Password" name="password" required></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>
                                            <button type="submit" class="btn-lg">Login</button>@*<span style="padding-left:20%">
                        <input type="checkbox" checked="checked"> Remember me
                    </span>*@
                                        </td>
                                    </tr>
                                </table>
                            </div>

                            <div style="background-color:#f1f1f1">
                                
                                <input type="checkbox" checked="checked"> Remember me
                                @*<button type="button" class="cancelbtn">Cancel</button>*@
                                <span style="float:right">Forgot <a href="#">password?</a></span>
                                   
                            </div>
                        }

                    </div>
                    @*<div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>*@
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div>
                    
        
        </ul>
        </nav>

        <div class="clear"></div>
    </div>
		</div>
		<header>
        
			<div class="width">
            <div><a href="/Addfreepost/Index" id="addbutton">ফ্রী এড পোস্ট করুন</a></div>
				<h2>স্বাগতম সেল মি ওয়েবসাইটে!<span></span></h2>
				<div class="tagline">
					<p>Welcome to Sell Me.com - the largest marketplace in Bangladesh.Buy and sell everything from used cars to mobile phones and computers, or search for property, jobs and more in Bangladesh - for free!.Select a region below to get started:
</p>
				</div>
			</div>
		</header>
        <section id="body" class="width clear">

        <table border="0">
    <tr>
    <td id="menu"> 
			<aside id="sidebar" class="column-left">
            
            @foreach (var i in Users)
            {
                if (i.parentid != 0)
                {
                }

                else
                {
                    <ul class="blocklist">
                    <li class="selected-item"><h4>@i.name</h4>
                    </ul>
                        
                }
                foreach (var item in Users.Where(a => a.parentid == i.id))
                {
                 
                <li class="blocklist">
                <a>@Html.ActionLink(item.menu2.name, item.navurl, i.menu2.name)</a>             
                </li>
                
                
                }
            }
                </td><td id="content">@RenderBody()</td></tr>
        
    </table>
            
	</ul>
			</aside>
			

pro/pro/Views/Shared/second.cshtml
@using pro.Models
@{
    dbaseEntities1 db = new dbaseEntities1();
    List<city> cities = db.cities.OrderBy(x => x.cityname).ToList();
    ViewBag.city = cities;
    
    }
    <script src="~/Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>

<script type="text/javascript">
    function load() {
        var value = $("#ddlstate").val();

        if (value != "Select") {
            $.ajax({
                url: '@Url.Action("area", "extra")',
                type: 'POST',
                data: { "selectedvalue": value },

                dataType: 'Json',
                success: function (response) {
                    var items = "";

                    $.each(response.Objcity, function (i, item) {
                        items += "<option value=\"" + item + "\">" + item + "</option>";
                    });
                       $("#city").html(items);
                },
                error: function (error) {
                }
            });
        }

    }
         
        
        
</script>
<fieldset>
        <legend></legend>
        <br />

        <div class="editor-label">
            @Html.LabelFor(model =>cities)
        </div>
        <div class="editor-field">
@Html.DropDownList("ddlstate", new SelectList(ViewBag.city, "id", "cityname"),"Select City Name",new { onchange = "load()"})
</div>
    <br />
    <div class="editor-label">
            @Html.Label("area")
        </div>
    <select id="city" name="area" style="width: 200px">

    </select>
     
        