pro/pro/Models/camera.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace pro.Models
{
    [MetadataType(typeof(cameraMetaData))]
    public partial class camera
    {
        [Compare("phone")]
        public string confirmphone { get; set; }

        public class cameraMetaData
        {
            [Required]
            public string phone { get; set; }

            [Required]
            public string brandname { get; set; }
        }
    }
}

pro/pro/Models/car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.DynamicData;

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
namespace pro.Models
{
    [MetadataType(typeof(carMetaData))]
    public partial class car
    {
        [Compare("password")]
        public string retypepass { get; set; }

        public class carMetaData
        {
            [Required(),StringLength(25)]
            public string brand { get; set; }
            [Required()]
            public string password { get; set; }
            
            [Required()]
            public string phone { get; set; }
            [Required()]
            [RegularExpression(@"[\w|.|-]*@\w*\.[\w|.]*", ErrorMessage = "*  Please Insert Correct Email")]
            public string email { get; set; }
            [Required()]
            public string price { get; set; }
            [Required()]
            public string area { get; set; }
        }
    }
}

pro/pro/Models/mobile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace pro.Models
{
    [MetadataType(typeof(mobileMetaData))]
    public partial class mobile
    {
        public class  mobileMetaData
        {
            [Required]
            public string brandname { get; set; }
            [Required]
            public string modelno { get; set; }
            

            [Required]
            public double price { get; set; } 

             
        }
        


    }
}

pro/pro/Controllers/AddfreepostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using pro.Models;
using System.IO;

namespace pro.Controllers
{
    public class AddfreepostController : Controller
    {
      
        dbaseEntities1 db = new dbaseEntities1();
        //
        // GET: /Addfreepost/
        
         public ActionResult Index()
        {
            @ViewBag.data = db.menus.OrderBy(y => y.name).Where(x => x.parentid != 0);
           
            return View();
        }
   
    [HttpPost]
        public ActionResult Create(car car,HttpPostedFileBase file,int ddlstate,string area)
        {
        if (file.ContentLength > 0)
    {
        var fileName = Path.GetFileName(file.FileName);
        var path = Path.Combine(Server.MapPath("~/photo"), fileName);
        file.SaveAs(path);
        car.image = "~/photo/" + file.FileName;
        ViewBag.msg = "Your Add has been Posted";
    }  
            car.poston = DateTime.Now;
            car.status = "post";
            //car.cityid = ddlstate;
            car.area = area;
           
            db.cars.AddObject(car);
            db.SaveChanges();

            return View("Index");
        }
    [HttpPost]
    public ActionResult Createcamera(camera camera, HttpPostedFileBase file)
    {
        if (ModelState.IsValid)
        {
            if (file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/photo"), fileName);
                file.SaveAs(path);
                camera.image = "~/photo/" + file.FileName;

            }
            camera.posttime = DateTime.Now;
            camera.status = "pending";



            db.cameras.AddObject(camera);
            db.SaveChanges();
            @ViewBag.msg = "Your Add has been Posted For Review";
            return View("Index");
            
        }
        return View("Createcamera", "_layout", camera);
        
    }
    [HttpPost]
    public ActionResult Createmobile(mobile mobile, HttpPostedFileBase file)
    {
        if (file.ContentLength > 0)
        {
            var fileName = Path.GetFileName(file.FileName);
            var path = Path.Combine(Server.MapPath("~/photo"), fileName);
            file.SaveAs(path);
            mobile.image = "~/photo/" + file.FileName;
        }
        mobile.poston = DateTime.Now.ToString();
        mobile.status = "pending";

        db.mobiles.AddObject(mobile);
        db.SaveChanges();
        @ViewBag.msg = "Your Add has been Sent To Admin Panel For Review";
        return View("Index");
    }
        public ActionResult createland(land land)
        {
            
            land.poston = DateTime.Now;
            land.status = "post";
            //land.image = ;
            db.lands.AddObject(land);
            db.SaveChanges();
            @ViewBag.msg = "Your Add has been Posted";
            return View("Index");
        }
        
        public ActionResult createfurniture(furniture fur)
        {
           
            fur.poston = DateTime.Now;
            fur.status = "post";
            //land.image = ;
            db.furnitures.AddObject(fur);
            db.SaveChanges();
            @ViewBag.msg = "Your Add has been Posted";
            return View("Index");
        }
        //[HttpGet]
       // [ActionName("Category")]
        public ActionResult Categorydetails(string name)
        {
            @ViewBag.msg = "";
            System.Threading.Thread.Sleep(2000);
            return PartialView(name);
           
        }
       
    }
}

            
            
           
        
       
    

pro/pro/Views/Addfreepost/Camera.cshtml
@model  pro.Models.camera

@{
    
    ViewBag.Title = "Camera";
}
<style>
    .field-validation-error {
        color: #D70800;
        font-weight: bold;
    }
</style>
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<h2></h2>

@using (Html.BeginForm("Createcamera", "Addfreepost",FormMethod.Post, new { enctype="multipart/form-data", data_ajax="false"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.brandname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.brandname)
            @Html.ValidationMessageFor(model => model.brandname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.price)
            @Html.ValidationMessageFor(model => model.price)
        </div>
         <div class="editor-label">
            @Html.LabelFor(model => model.image)
        </div>
        <p><input type='file' name='file' id='file' /></p>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.location)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.phone)
            @Html.ValidationMessageFor(model => model.phone)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.confirmphone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.confirmphone)
            @Html.ValidationMessageFor(model => model.confirmphone)
        </div>
        @Html.Partial("second");
  
       
        <p>
            <input type="submit" value="Create" name="Create"/>
        </p>
    </fieldset>
}



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    
}

pro/pro/Views/Addfreepost/Camera1.cshtml
<h1>Cam</h1>

pro/pro/Views/Addfreepost/Car.cshtml
@model pro.Models.car

@{
    ViewBag.Title = "Car";
}

<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />*@
<style>
    .field-validation-error {
        color: #D70800;
        font-weight: bold;
    }
</style>
<h2>Car</h2>

@using (Html.BeginForm("Create", "Addfreepost",FormMethod.Post, new { enctype="multipart/form-data", data_ajax="false"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.brand)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.brand)
            @Html.ValidationMessageFor(model => model.brand)
        </div>
         <div class="editor-label">
            @Html.LabelFor(model => model.image)
        </div>
        <p><input type='file' name='file' id='file' /></p>

        <div class="editor-label">
            @Html.LabelFor(model => model.price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.price)
            @Html.ValidationMessageFor(model => model.price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.phone)
            @Html.ValidationMessageFor(model => model.phone)
        </div>   
         @Html.Partial("second")
         <div class="editor-label">
            @Html.LabelFor(model => model.email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.email)
            @Html.ValidationMessageFor(model => model.email)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.password)
            @Html.ValidationMessageFor(model => model.password)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.retypepass)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.retypepass)
            @Html.ValidationMessageFor(model => model.retypepass)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
   
}

pro/pro/Views/Addfreepost/House.cshtml
@model pro.Models.house

@{
    ViewBag.Title = "House";
}

<h2></h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.address)
            @Html.ValidationMessageFor(model => model.address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.housesize)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.housesize)
            @Html.ValidationMessageFor(model => model.housesize)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.description)
            @Html.ValidationMessageFor(model => model.description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.price)
            @Html.ValidationMessageFor(model => model.price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.location)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.image)
        </div>
        

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pro/pro/Views/Addfreepost/Index.cshtml
@model IEnumerable<pro.Models.menu>
@using pro.Models;

@{
    dbaseEntities1 db = new dbaseEntities1();
    Layout = "~/Views/Shared/_layout.cshtml";
   //ViewBag.data = db.menus.Select(men => new { name = men.menu1.name }).ToList();
    ViewBag.data = db.menus.OrderBy(y => y.name).Where(x => x.parentid != 0);
    //ViewBag.msg = "Your Add has been Sent To admin if admin confirms your add will be visible";
}
<style type="text/css">

#abc
{
    margin-left:43%;
    
    margin-top:35px;
    display:table; 
   
}
.dropdown 
{
   width:250px;
   height:30px;
   font-size:large;
}
#msg
{
    text-align:center;
    border:solid 1px green;
    color:Green;
    height:40px;
}

</style>
<script src="../../Scripts/jquery-2.1.1.min.js" type="text/javascript"></script>

<script src="../../Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>


<html>
<head runat="server">
    <script src="../../Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
    <script type="text/javascript">
     
    
        function loadPartial() 
        {
            var name = $("#Category").val();
            //sleep(2);
            $("#abc").html('<img src="../../photo/spiffygif_30x30.gif" alt="Loading, please wait" />');
           @* alert(name);*@
            $("#abc").load('/Addfreepost/Categorydetails/?name=' + name);
            
        }
        
    </script>
    <title>Index</title>
</head>
<body>
@if (ViewBag.msg != null)
{
       <div id="msg">
         <h5>  @ViewBag.msg</h5>
       </div>
}

<div align="center">
<h1>Please Select a Category</h1>
<h1>.</h1>

   @Html.DropDownList("Category", new SelectList(ViewBag.data, "name", "name"),"", new { @class="dropdown", onchange = "loadPartial()" })
</div>

<div id="load"></div>
<div id="abc"></div>

    </body>
</html>

pro/pro/Views/Addfreepost/Job.cshtml
@model pro.Models.job

@{
    ViewBag.Title = "job";
}

<h2></h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.category)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.category)
            @Html.ValidationMessageFor(model => model.category)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jobtype)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jobtype)
            @Html.ValidationMessageFor(model => model.jobtype)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.website)
            @Html.ValidationMessageFor(model => model.website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.phone)
            @Html.ValidationMessageFor(model => model.phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.salary)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.salary)
            @Html.ValidationMessageFor(model => model.salary)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jobtitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jobtitle)
            @Html.ValidationMessageFor(model => model.jobtitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.description)
            @Html.ValidationMessageFor(model => model.description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.coname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.coname)
            @Html.ValidationMessageFor(model => model.coname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.location)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location)
        </div>

       

        

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pro/pro/Views/Addfreepost/Mobile.cshtml
@model pro.Models.mobile
@{
    ViewBag.Title = "Camera";
    Layout = null;
}

<script src="../../Content/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm("Createmobile","Addfreepost", FormMethod.Post, new { enctype = "multipart/form-data", data_ajax = "false" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.brandname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.brandname)
            @Html.ValidationMessageFor(model => model.brandname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.modelno)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.modelno)
            @Html.ValidationMessageFor(model => model.modelno)
        </div>
          <div class="editor-label">
            @Html.LabelFor(model => model.image)
        </div>
        <p><input type='file' name='file' id='file' /></p>

        <div class="editor-label">
            @Html.LabelFor(model => model.price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.price)
            @Html.ValidationMessageFor(model => model.price)
        </div>

        

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pro/pro/Views/Addfreepost/furniture.cshtml
@model pro.Models.furniture

@{
    ViewBag.Title = "furniture";
}

<h2></h2>

@using (Html.BeginForm("createfurniture", "Addfreepost"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.description)
            @Html.ValidationMessageFor(model => model.description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.price)
            @Html.ValidationMessageFor(model => model.price)
        </div>

       
        

        <div class="editor-label">
            @Html.LabelFor(model => model.location)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location)
        </div>

       

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pro/pro/Views/Addfreepost/land.cshtml
@model pro.Models.land

@{
    ViewBag.Title = "land";
}

<h2></h2>

@using (Html.BeginForm("createland", "Addfreepost"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        
        

        <div class="editor-label">
            @Html.LabelFor(model => model.location)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location)
        </div>

        <p>
            <input type="submit" value="Create"  />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
   
}