pro/pro/Models/camera.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace pro.Models
{
    [MetadataType(typeof(cameraMetaData))]
    public partial class camera
    {
        [Compare("phone")]
        public string confirmphone { get; set; }

        public class cameraMetaData
        {
            [Required]
            public string phone { get; set; }

            [Required]
            public string brandname { get; set; }
        }
    }
}

pro/pro/Models/mobile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace pro.Models
{
    [MetadataType(typeof(mobileMetaData))]
    public partial class mobile
    {
        public class  mobileMetaData
        {
            [Required]
            public string brandname { get; set; }
            [Required]
            public string modelno { get; set; }
            

            [Required]
            public double price { get; set; } 

             
        }
        


    }
}

pro/pro/Controllers/ViewDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using pro.Models;
using System.Text;
//using System.Web.Mail;
using System.Net.Mail;
using System.Net;
//using System.Net.Mail;
namespace pro.Controllers
{
    public class ViewDetailsController : Controller
    {
        //
        // GET: /ViewDetails/

        public ActionResult Index(string name, int id)
        {
            if(Session["username"]==null)
            {
                return RedirectToAction("Index", "login");
            }
            @ViewBag.user = Session["username"];
            //if (TempData["msg"] != null)
            //{
            //    string msg=TempData["msg"].ToString();
            //    ViewBag.msg = msg; 
            //}
            dbaseEntities1 db = new dbaseEntities1();
            if (name == "Camera")
            {
                return PartialView(name, db.cameras.Single(c => c.id == id));
            }
            if (name == "Mobile")
            {
                return PartialView(name, db.mobiles.Single(c => c.id == id));
            }

           
            return View();
        }
        [HttpPost]
        public ActionResult succcessmail(FormCollection fc)
        {
            int id=Convert.ToInt32(fc["modelid"]);
            StringBuilder sb = new StringBuilder();
            sb.Append("Dear Sir,<br/><br/>");
            sb.Append("Your Add Has SuccessFully Been Posted At Our WebSite.You can Watch Your Add By Clicking The Following Link Given");
            sb.Append("<br/>");
            sb.Append("http://localhost:4077/details/CameraDetails/" + fc["modelid"].ToString());
            sb.Append("<br/><br/>");
            sb.Append("<b>Sell Me</b>");
            var server = new SmtpClient();
            server.Host = "smtp.gmail.com";
            server.Port = 587;
            server.UseDefaultCredentials = false;
            server.Credentials = new System.Net.NetworkCredential("thirdnazim@gmail.com", "daimond1");
            server.EnableSsl = true;
            var email = new MailMessage();
            MailAddress me = new MailAddress("doublenazim@gmail.com");
            email.From = me;
            email.To.Add(fc["rmail"].ToString());
            email.Subject = fc["subject"].ToString();
            email.Body =sb.ToString() ;
            email.IsBodyHtml = true;
            try
            {
                server.Send(email);
            }
            catch (SmtpFailedRecipientException error)
            {
                //MessageBox.Show("error: " + error.Message + "\nFailing recipient: " + error.FailedRecipient);
            }
            ViewBag.msg = "message sent";
            dbaseEntities1 db = new dbaseEntities1();
            camera c = db.cameras.SingleOrDefault(a => a.id ==id);
            c.status = "post";
            c.posttime = System.DateTime.Now;
            db.SaveChanges();
            TempData["msg"] = "Add And Email Has SuccessFully Been Posted";
            return RedirectToAction("Ads", "Admin", new {name="Camera" });


            return View();
        }
        public ActionResult unsucccessmail(FormCollection fc)
        {
            int id = Convert.ToInt32(fc["modelid"]);
            StringBuilder sb = new StringBuilder();
            sb.Append("Dear Sir,<br/><br/>");
            sb.Append("Your Add Has SuccessFully Been Deleted From Our WebSite From Our Terms & ConDition.You can Check our Add Policy By Clicking The Following Link Given");
            //sb.Append("<br/>");
            //sb.Append("http://localhost:4077/details/CameraDetails/" + fc["modelid"].ToString());
            sb.Append("<br/><br/>");
            sb.Append("<b>Sell Me</b>");
            var server = new SmtpClient();
            server.Host = "smtp.gmail.com";
            server.Port = 587;
            server.UseDefaultCredentials = false;
            server.Credentials = new System.Net.NetworkCredential("thirdnazim@gmail.com", "daimond1");
            server.EnableSsl = true;
            var email = new MailMessage();
            MailAddress me = new MailAddress("doublenazim@gmail.com","AdminSellMe");
            email.From = me;
            email.To.Add(fc["rmail"].ToString());
            email.Subject = fc["subject"].ToString();
            email.Body = sb.ToString();
            email.IsBodyHtml = true;
            try
            {
                server.Send(email);
            }
            catch (SmtpFailedRecipientException error)
            {
                //MessageBox.Show("error: " + error.Message + "\nFailing recipient: " + error.FailedRecipient);
            }
            ViewBag.msg = "message sent";
            dbaseEntities1 db = new dbaseEntities1();
            camera c = db.cameras.SingleOrDefault(a => a.id == id);
            db.cameras.DeleteObject(c);
            //c.status = "post";
           // c.posttime = System.DateTime.Now;
            db.SaveChanges();
            TempData["msg"] = "Add Deleted And Email Sent";
            return RedirectToAction("Ads", "Admin", new { name = "Camera" });


            return View();
        }
        [HttpPost]
        public ActionResult MobileSucccessmail(FormCollection fc)
        {
            int id = Convert.ToInt32(fc["modelid"]);
            StringBuilder sb = new StringBuilder();
            sb.Append("Dear Sir,<br/><br/>");
            sb.Append("Your Add Has SuccessFully Been Posted At Our WebSite.You can Watch Your Add By Clicking The Following Link Given");
            sb.Append("<br/>");
            sb.Append("http://localhost:4077/details/MobileDetails/" + fc["modelid"].ToString());
            sb.Append("<br/><br/>");
            sb.Append("<b>Sell Me</b>");
            var server = new SmtpClient();
            server.Host = "smtp.gmail.com";
            server.Port = 587;
            server.UseDefaultCredentials = false;
            server.Credentials = new System.Net.NetworkCredential("doublenazim@gmail.com", "city.nazim20");
            server.EnableSsl = true;
            var email = new MailMessage();
            MailAddress me = new MailAddress("doublenazim@gmail.com");
            email.From = me;
            email.To.Add(fc["rmail"].ToString());
            email.Subject = fc["subject"].ToString();
            email.Body = sb.ToString();
            email.IsBodyHtml = true;
            try
            {
                server.Send(email);
            }
            catch (SmtpFailedRecipientException error)
            {
                //MessageBox.Show("error: " + error.Message + "\nFailing recipient: " + error.FailedRecipient);
            }
            ViewBag.msg = "message sent";
            dbaseEntities1 db = new dbaseEntities1();
            mobile m = db.mobiles.SingleOrDefault(a => a.id == id);
            m.status = "post";
            m.poston = System.DateTime.Now.ToString();
            db.SaveChanges();
            TempData["msg"] = "Add And Email Has SuccessFully Been Posted";
            return RedirectToAction("Ads", "Admin", new { name = "Mobile" });


            return View();
        }
        public ActionResult MobileUnsucccessmail(FormCollection fc)
        {
            int id = Convert.ToInt32(fc["modelid"]);
            StringBuilder sb = new StringBuilder();
            sb.Append("Dear Sir,<br/><br/>");
            sb.Append("Your Add Has SuccessFully Been Deleted From Our WebSite From Our Terms & ConDition.You can Check our Add Policy By Clicking The Following Link Given");
            //sb.Append("<br/>");
            //sb.Append("http://localhost:4077/details/MobileDetails/" + fc["modelid"].ToString());
            sb.Append("<br/><br/>");
            sb.Append("<b>Sell Me</b>");
            var server = new SmtpClient();
            server.Host = "smtp.gmail.com";
            server.Port = 587;
            server.UseDefaultCredentials = false;
            server.Credentials = new System.Net.NetworkCredential("thirdnazim@gmail.com", "daimond1");
            server.EnableSsl = true;
            var email = new MailMessage();
            MailAddress me = new MailAddress("doublenazim@gmail.com", "AdminSellMe");
            email.From = me;
            email.To.Add(fc["rmail"].ToString());
            email.Subject = fc["subject"].ToString();
            email.Body = sb.ToString();
            email.IsBodyHtml = true;
            try
            {
                server.Send(email);
            }
            catch (SmtpFailedRecipientException error)
            {
                //MessageBox.Show("error: " + error.Message + "\nFailing recipient: " + error.FailedRecipient);
            }
            ViewBag.msg = "message sent";
            dbaseEntities1 db = new dbaseEntities1();
            mobile m = db.mobiles.SingleOrDefault(a => a.id == id);
            db.mobiles.DeleteObject(m);
            db.SaveChanges();
            TempData["msg"] = "Add Deleted And Email Sent";
            return RedirectToAction("Ads", "Admin", new { name = "Mobile" });


            return View();
        }
    }
}

pro/pro/Views/ViewDetails/Camera.cshtml
@model pro.Models.camera
@{
    ViewBag.Title = "Camera";
    Layout = "~/Views/Shared/admin.cshtml";
}
<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <style type="text/css">
        #one {
            margin-left: 20%;
        }

        img {
            height: 150px;
            width: 150px;
        }
        td {
            height: 60px;
            
        }
        input {
            width: 300px;
            height:30px;
        }
        textarea {
            width: 400px;
            height: 150px;
        }
    </style>
    
</head>
<div id="one">
    <h2>Details</h2>

    <fieldset>
        <legend>camera</legend>

        <div><img src="@Url.Content(Model.image)" width="100px" height="100px" /></div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.brandname)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.brandname)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.price)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.price)
        </div>


        <div class="display-label">
            @Html.DisplayNameFor(model => model.posttime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.posttime)
        </div>


        <div class="display-label">
            @Html.DisplayNameFor(model => model.location)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.location)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.phone)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.phone)
        </div>
    </fieldset>
    <table>
        <tr>
    <p>

        @Html.ActionLink("Back to List", "Ads", "Admin", new { name = "Camera", page = 1 }, null);

    </p>
    </tr>

    <tr><td>

    <p><a data-toggle="modal" href="#MailModal1" class="btn btn-success"><b>Post & Send Mail</b></a></p>
</div>
@using (Html.BeginForm("succcessmail", "ViewDetails",FormMethod.Post))
{
<!-- Modal -->
<div class="modal fade" id="MailModal1" tabindex="-1" role="dialog" aria-labelledby="CmapModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">SuccessFull Mail</h4>
            </div>
            <div class="modal-body">
                <table><tr><td>@Html.Label("to", "To")</td><td>@Html.TextBox("Rmail","thirdnazim@gmail.com")</td></tr><tr></tr><tr><td>@Html.Label("subject", "subject")</td><td>@Html.TextBox("subject","Your Add Has SuccessFully Been Posted")</td></tr><tr></tr><tr><td>@Html.Label("body", "body")</td><td><textarea name="body"> Dear User Your Add Has SuccessFully Been Posted At Our WebSite.You can Watch Your Add By Clicking The Following Link Given @*<a href=<a rel="nofollow" href="http://localhost:8080/travel/t_form.jsp" target="_blank">http://localhost:8080/travel/t_form.jsp</a>*@</textarea></td></tr></table>
               ...
            </div>
            <div class="modal-footer">
                @Html.TextBox("modelid", Model.id, new { style = "display: none;" })
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Send Mail</button>
                
               
                @*@Html.ActionLink("Send Mail", "sendmail", "ViewDetails",null, new { @class = "button" })*@
            </div>
        
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
}
</div>


</td>
<td>
    <p><a data-toggle="modal" href="#MailModal2" class="btn btn-danger"><b>Reject & Send Mail</b></a></p>
    </div>
@using (Html.BeginForm("unsucccessmail", "ViewDetails",FormMethod.Post))
{
    <!-- Modal -->
    <div class="modal fade" id="MailModal2" tabindex="-1" role="dialog" aria-labelledby="CmapModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Delete product</h4>
                </div>
                <div class="modal-body">
                    <table><tr><td>@Html.Label("to", "To")</td><td>@Html.TextBox("Rmail", "thirdnazim@gmail.com")</td></tr><tr></tr><tr><td>@Html.Label("subject", "subject")</td><td>@Html.TextBox("subject", "We Can't Post Your Add")</td></tr><tr></tr><tr><td>@Html.Label("body", "body")</td><td><textarea name="body"> Dear User We Are Very Sorry That Your Add Has not Been Posted At Our WebSite Because our Terms & Conditons.You can Watch Your Add By Clicking The Following Link Given @*<a href=<a rel="nofollow" href="http://localhost:8080/travel/t_form.jsp" target="_blank">http://localhost:8080/travel/t_form.jsp</a>*@</textarea></td></tr></table>
                </div>
                <div class="modal-footer">
                    @Html.TextBox("modelid", Model.id, new { style = "display: none;" })
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete & Send Mail</button>
                    
                    @*<button type="button" class="btn btn-primary">Save changes</button>*@
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    
}
</td>
<td></td>
</tr>
</table>
</html>

pro/pro/Views/ViewDetails/Mobile.cshtml
@model pro.Models.mobile
@{
    ViewBag.Title = "Mobile";
    Layout = "~/Views/Shared/admin.cshtml";
}
<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <style type="text/css">
        #one {
            margin-left: 20%;
        }

        img {
            height: 150px;
            width: 150px;
        }

        td {
            height: 60px;
        }

        input {
            width: 300px;
            height: 30px;
        }

        textarea {
            width: 400px;
            height: 150px;
        }
    </style>

</head>
<div id="one">
    <h2>Details</h2>

    <fieldset>
        <legend>camera</legend>

        <div><img src="@Url.Content(Model.image)" width="100px" height="100px" /></div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.brandname)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.brandname)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.price)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.price)
        </div>


        <div class="display-label">
            @Html.DisplayNameFor(model => model.poston)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.poston)
        </div>


        

        <div class="display-label">
            @Html.DisplayNameFor(model => model.modelno)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.modelno)
        </div>
    </fieldset>
    <table>
        <tr>
            <p>

                @Html.ActionLink("Back to List", "Ads", "Admin", new { name = "Mobile", page = 1 }, null);

            </p>
        </tr>

        <tr>
            <td>

                <p><a data-toggle="modal" href="#MailModal1" class="btn btn-success"><b>Post & Send Mail</b></a></p>
</div>
@using (Html.BeginForm("MobileSucccessmail", "ViewDetails", FormMethod.Post))
{
    <!-- Modal -->
    <div class="modal fade" id="MailModal1" tabindex="-1" role="dialog" aria-labelledby="CmapModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">SuccessFull Mail</h4>
                </div>
                <div class="modal-body">
                    <table><tr><td>@Html.Label("to", "To")</td><td>@Html.TextBox("Rmail", "thirdnazim@gmail.com")</td></tr><tr></tr><tr><td>@Html.Label("subject", "subject")</td><td>@Html.TextBox("subject", "Your Add Has SuccessFully Been Posted")</td></tr><tr></tr><tr><td>@Html.Label("body", "body")</td><td><textarea name="body"> Dear User Your Add Has SuccessFully Been Posted At Our WebSite.You can Watch Your Add By Clicking The Following Link Given @*<a href=<a rel="nofollow" href="http://localhost:8080/travel/t_form.jsp" target="_blank">http://localhost:8080/travel/t_form.jsp</a>*@</textarea></td></tr></table>
                    ...
                </div>
                <div class="modal-footer">
                    @Html.TextBox("modelid", Model.id, new { style = "display: none;" })
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Send Mail</button>


                    @*@Html.ActionLink("Send Mail", "sendmail", "ViewDetails",null, new { @class = "button" })*@
                </div>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
}
</div>


</td>
<td>
    <p><a data-toggle="modal" href="#MailModal2" class="btn btn-danger"><b>Reject & Send Mail</b></a></p>
    </div>
    @using (Html.BeginForm("MobileUnsucccessmail", "ViewDetails", FormMethod.Post))
    {
    <!-- Modal -->
        <div class="modal fade" id="MailModal2" tabindex="-1" role="dialog" aria-labelledby="CmapModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Delete product</h4>
                    </div>
                    <div class="modal-body">
                        <table><tr><td>@Html.Label("to", "To")</td><td>@Html.TextBox("Rmail", "thirdnazim@gmail.com")</td></tr><tr></tr><tr><td>@Html.Label("subject", "subject")</td><td>@Html.TextBox("subject", "We Can't Post Your Add")</td></tr><tr></tr><tr><td>@Html.Label("body", "body")</td><td><textarea name="body"> Dear User We Are Very Sorry That Your Add Has not Been Posted At Our WebSite Because our Terms & Conditons.You can Watch Your Add By Clicking The Following Link Given @*<a href=<a rel="nofollow" href="http://localhost:8080/travel/t_form.jsp" target="_blank">http://localhost:8080/travel/t_form.jsp</a>*@</textarea></td></tr></table>
                    </div>
                    <div class="modal-footer">
                        @Html.TextBox("modelid", Model.id, new { style = "display: none;" })
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete & Send Mail</button>

                        @*<button type="button" class="btn btn-primary">Save changes</button>*@
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

    }
</td>
<td></td>
</tr>
</table>
</html>